name: rerefined
version: 0.0.0
synopsis: Refinement types
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
category: Types, Data
license: MIT
license-file: LICENSE
#tested-with:
#- GHC==9.8
#- GHC==9.6
#- GHC==9.4
#- GHC==9.2

github: raehik/rerefined
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

# raehik's extensions (GHC 9.2; last updated: 2022-10-09)
language: GHC2021
default-extensions:
# syntax that should be default
- LambdaCase
- NoStarIsType

## deriving-related
- DerivingVia # implies DerivingStrategies
- DeriveAnyClass

# features that should be default
- GADTs
- RoleAnnotations

# other features
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash

# useful extensions to know about, but which should be specified on-demand
#
# UndecidableInstances:
#   required for type class wizardry
#   generally only enable if you were expecting to & compilation fails without
# AllowAmbiguousTypes:
#   often goes hand in hand with TypeApplications-heavy code
#   enabling on demand brings attention to the sort of functions to expect
# StarIsType:
#   may need to enable if you're working with old code that uses `Int :: *`

ghc-options:
- -Wall

# omitting ticks is good; see https://gitlab.haskell.org/ghc/ghc/-/issues/20531
# (off by default since GHC 9.4)
- -Wno-unticked-promoted-constructors

dependencies:
- base >= 4.16 && < 5
- typeably ^>= 0.1.0
- mono-traversable ^>= 1.0.17.0
- template-haskell # TODO

library:
  source-dirs: src
